title: Your awesome title
email: your-email@domain.com
description: The description
baseurl: ""
url: ""
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
